import Head from 'next/head'
import Image from 'next/image'
import Layout from './components/Layout'
import OverviewSection from './components/OverviewSection'
import HighlightSection from './components/HighlightSection'
import PortfolioSection from './components/PortfolioSection'
import ProjectsSection from './components/ProjectsSection'
import ContactSection from './components/ContactSection'

export default function Home() {
  function scrollToTop(e) {
    console.log(e)
  }

  return (
    <>
      <Head>
        <title>Todd Rizzolo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://use.fontawesome.com/releases/v5.7.0/css/all.css'
          rel='stylesheet'
        />
      </Head>

      <Layout>
        <OverviewSection />
        <HighlightSection />
        <PortfolioSection />
        <ProjectsSection />
        <ContactSection />
        <section>
          <a href='#' onClick={(e) => scrollToTop(e)}>
            <i aria-hidden className='fas fa-angle-double-up'></i> Back to top
          </a>
        </section>
      </Layout>
    </>
  )
}
