import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Layout from './components/Layout'
import OverviewSection from './components/OverviewSection'
import HighlightSection from './components/HighlightSection'
import PortfolioSection from './components/PortfolioSection'
import ProjectsSection from './components/ProjectsSection'
import ContactSection from './components/ContactSection'

export default function Home() {
  const [theme, toggleTheme] = useState('light')
  const inactiveTheme = theme === 'light' ? 'dark' : 'light'

  function scrollToTop(e) {
    console.log(e)
  }

  useEffect(() => {
    const theme = window.localStorage.getItem('theme')
    theme && toggleTheme(theme)
  }, [])

  useEffect(() => {
    document.body.dataset.theme = theme
    window.localStorage.setItem('theme', theme)
  }, [theme])

  return (
    <>
      <Head>
        <title>Todd Rizzolo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://use.fontawesome.com/releases/v5.7.0/css/all.css'
          rel='stylesheet'
        />
      </Head>

      <Layout>
        <div style={{ position: 'absolute', top: '3rem', right: '3rem' }}>
          {theme === 'light' ? (
            <button onClick={() => toggleTheme('dark')}>
              <i aria-hidden className='fas fa-cloud-sun'></i> Light Theme
            </button>
          ) : (
            <button onClick={() => toggleTheme('light')}>
              <i aria-hidden className='fas fa-moon'></i> Dark Theme
            </button>
          )}
        </div>
        <OverviewSection />
        <HighlightSection />
        <PortfolioSection />
        <ProjectsSection />
        <ContactSection />
        <section>
          <a href='#' onClick={(e) => scrollToTop(e)}>
            <i aria-hidden className='fas fa-angle-double-up'></i> Back to top
          </a>
        </section>
      </Layout>
    </>
  )
}
