import Head from 'next/head'
import Image from 'next/image'
import Layout from './components/Layout'

export default function Home() {
  function scrollToTop(e) {
    console.log(e)
  }

  return (
    <>
      <Head>
        <title>Todd Rizzolo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <section>
          <a href='#' onClick={(e) => scrollToTop(e)}>
            <i aria-hidden className='fas fa-angle-double-up'></i> Back to top
          </a>
        </section>
      </Layout>
    </>
  )
}
